//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uch.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Uche
    {
        public string Name { get; set; }
        public string RegNum { get; set; }
        public string Year { get; set; }
        public string Color { get; set; }
    }
}
